---
all:
  children:
    iosxr:
      children:
        p_routers:
          hosts:
            P1:
              ansible_host: 10.255.231.1

            P2:
              ansible_host: 10.255.231.2

            P3:
              ansible_host: 10.255.231.3

            P4:
              ansible_host: 10.255.231.4

            P5:
              ansible_host: 10.255.231.5

            P6:
              ansible_host: 10.255.231.6

            P7:
              ansible_host: 10.255.231.7

            P8:
              ansible_host: 10.255.231.8

            P9:
              ansible_host: 10.255.231.9

            P10:
              ansible_host: 10.255.231.10

            P11-RR-SHADOW:
              ansible_host: 10.255.231.11

            P12-RR-PRIMARY:
              ansible_host: 10.255.231.12

            P23-PCE:
              ansible_host: 10.255.231.23

        pe_routers:
          hosts:
            PE1:
              ansible_host: 10.255.231.101

            PE4:
              ansible_host: 10.255.231.104

      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        ansible_network_cli_ssh_type: libssh
        ansible_user: "{{ lookup('env', 'NETOPS_USER') }}"
        ansible_password: "{{ lookup('env', 'NETOPS_PASSWORD') }}"
        ansible_ssh_common_args: >-
          -o HostKeyAlgorithms=+ssh-rsa
          -o StrictHostKeyChecking=no
